# frozen_string_literal: true

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - '.git/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'benchmark/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'benchmark/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Enabled: true

RSpec/ContextWording:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Capybara/RSpec/PredicateMatcher:
  Enabled: false
